AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Slackbot to prove out CI pipeline
Resources:
  SlackbotLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: SlackbotLambda.lambda_handler
      Timeout: 300
      Runtime: python3.6
